version: '3.9'
services:
  frontend:
    build: 
      context: ./frontend
      args:
        API_PATH: "http://localhost:${API_PORT}"
    ports:
      - '${WEBINTERFACE_PORT}:80'
    environment:
      - API_PATH="http://localhost:${API_PORT}"
  backend:
    build: ./backend
    ports: 
      - "${API_PORT}:8080"
    expose:
      - "${API_PORT}"
    volumes:
        - type: bind
          source: ${CONFIG_FILE_SOURCE} 
          target: /app/config.json
        - type: bind
          source: ${RESULT_DIR_SOURCE}
          target: ${RESULT_DIR_TARGET} 
        - type: bind
          source: ${DESCRIPTION_DIR_SOURCE}
          target: ${DESCRIPTION_DIR_TARGET} 
        - type: bind
          source: ${MALLOB_DIR_SOURCE}
          target: ${MALLOB_DIR_TARGET}
        - type: bind
          source: ${DATABASE_SOURCE}
          target: ${DATABASE_TARGET}
