version: '3.7'
services:
  frontend:
    build: ./frontend
    ports:
      - '1337:80'
    environment:
      REACT_APP_API_BASE_PATH: "http://localhost:8080"

  backend:
    build: ./backend
    ports: 
      - "8080:8080"
    expose:
      - "8080"
    volumes:
        - type: bind
          source: ${CONFIG_FILE_SOURCE} 
          target: /app/config.json
        - type: bind
          source: ${RESULT_DIR_SOURCE}
          target: ${RESULT_DIR_TARGET} 
        - type: bind
          source: ${DESCRIPTION_DIR_SOURCE}
          target: ${DESCRIPTION_DIR_TARGET} 
        - type: bind
          source: ${MALLOB_DIR_SOURCE}
          target: ${MALLOB_DIR_TARGET}
        - type: bind
          source: ${DATABASE_SOURCE}
          target: ${DATABASE_TARGET}
