# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend checks

on:
  push:
    branches:
      - '**'        # matches every branch
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: ./frontend
    - name: install dependencies
      working-directory: ./frontend
      run: npm ci
    - name: run tests 
      working-directory: ./frontend
      run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: ./frontend
    - name: install dependencies
      working-directory: ./frontend
      run: npm  ci
    - name: build
      working-directory: ./frontend
      run: npm run build
